// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getConfigByUserID = `-- name: GetConfigByUserID :one
SELECT user_id, for_trigger, against_trigger, left_label, right_label,
       decay_speed, created_at, updated_at
FROM configs WHERE user_id = $1
`

func (q *Queries) GetConfigByUserID(ctx context.Context, userID uuid.UUID) (Config, error) {
	row := q.db.QueryRow(ctx, getConfigByUserID, userID)
	var i Config
	err := row.Scan(
		&i.UserID,
		&i.ForTrigger,
		&i.AgainstTrigger,
		&i.LeftLabel,
		&i.RightLabel,
		&i.DecaySpeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE configs
SET for_trigger = $1, against_trigger = $2, left_label = $3,
    right_label = $4, decay_speed = $5, updated_at = NOW()
WHERE user_id = $6
`

type UpdateConfigParams struct {
	ForTrigger     string
	AgainstTrigger string
	LeftLabel      string
	RightLabel     string
	DecaySpeed     float64
	UserID         uuid.UUID
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.Exec(ctx, updateConfig,
		arg.ForTrigger,
		arg.AgainstTrigger,
		arg.LeftLabel,
		arg.RightLabel,
		arg.DecaySpeed,
		arg.UserID,
	)
	return err
}
