// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: eventsub.sql

package sqlcgen

import (
	"context"

	"github.com/pscheid92/uuid"
)

const createEventSubSubscription = `-- name: CreateEventSubSubscription :exec
INSERT INTO eventsub_subscriptions (
    user_id,
    broadcaster_user_id,
    subscription_id,
    conduit_id,
    created_at
)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE
    SET broadcaster_user_id = EXCLUDED.broadcaster_user_id,
        subscription_id     = EXCLUDED.subscription_id,
        conduit_id          = EXCLUDED.conduit_id
`

type CreateEventSubSubscriptionParams struct {
	UserID            uuid.UUID
	BroadcasterUserID string
	SubscriptionID    string
	ConduitID         string
}

func (q *Queries) CreateEventSubSubscription(ctx context.Context, arg CreateEventSubSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createEventSubSubscription,
		arg.UserID,
		arg.BroadcasterUserID,
		arg.SubscriptionID,
		arg.ConduitID,
	)
	return err
}

const deleteEventSubByUserID = `-- name: DeleteEventSubByUserID :exec
DELETE
FROM eventsub_subscriptions
WHERE user_id = $1
`

func (q *Queries) DeleteEventSubByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventSubByUserID, userID)
	return err
}

const getEventSubByUserID = `-- name: GetEventSubByUserID :one
SELECT user_id,
       broadcaster_user_id,
       subscription_id,
       conduit_id,
       created_at
FROM eventsub_subscriptions
WHERE user_id = $1
`

func (q *Queries) GetEventSubByUserID(ctx context.Context, userID uuid.UUID) (EventsubSubscription, error) {
	row := q.db.QueryRow(ctx, getEventSubByUserID, userID)
	var i EventsubSubscription
	err := row.Scan(
		&i.UserID,
		&i.BroadcasterUserID,
		&i.SubscriptionID,
		&i.ConduitID,
		&i.CreatedAt,
	)
	return i, err
}

const listEventSubSubscriptions = `-- name: ListEventSubSubscriptions :many
SELECT user_id,
       broadcaster_user_id,
       subscription_id,
       conduit_id,
       created_at
FROM eventsub_subscriptions
`

func (q *Queries) ListEventSubSubscriptions(ctx context.Context) ([]EventsubSubscription, error) {
	rows, err := q.db.Query(ctx, listEventSubSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsubSubscription{}
	for rows.Next() {
		var i EventsubSubscription
		if err := rows.Scan(
			&i.UserID,
			&i.BroadcasterUserID,
			&i.SubscriptionID,
			&i.ConduitID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
