// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Config struct {
	UserID         uuid.UUID
	ForTrigger     string
	AgainstTrigger string
	LeftLabel      string
	RightLabel     string
	DecaySpeed     float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
}

type EventsubSubscription struct {
	UserID            uuid.UUID
	BroadcasterUserID string
	SubscriptionID    string
	ConduitID         string
	CreatedAt         time.Time
}

type User struct {
	ID             uuid.UUID
	OverlayUUID    uuid.UUID
	TwitchUserID   string
	TwitchUsername string
	AccessToken    string
	RefreshToken   string
	TokenExpiry    time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
