// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configs.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/pscheid92/uuid"
)

const getConfigByBroadcasterID = `-- name: GetConfigByBroadcasterID :one
SELECT c.streamer_id,
       c.version,
       c.created_at,
       c.updated_at,
       c.for_trigger,
       c.for_label,
       c.against_trigger,
       c.against_label,
       c.memory_seconds,
       c.display_mode
FROM configs c
JOIN streamers s ON c.streamer_id = s.id
WHERE s.twitch_user_id = $1
`

type GetConfigByBroadcasterIDRow struct {
	StreamerID     uuid.UUID
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ForTrigger     string
	ForLabel       string
	AgainstTrigger string
	AgainstLabel   string
	MemorySeconds  int32
	DisplayMode    string
}

func (q *Queries) GetConfigByBroadcasterID(ctx context.Context, twitchUserID string) (GetConfigByBroadcasterIDRow, error) {
	row := q.db.QueryRow(ctx, getConfigByBroadcasterID, twitchUserID)
	var i GetConfigByBroadcasterIDRow
	err := row.Scan(
		&i.StreamerID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForTrigger,
		&i.ForLabel,
		&i.AgainstTrigger,
		&i.AgainstLabel,
		&i.MemorySeconds,
		&i.DisplayMode,
	)
	return i, err
}

const getConfigByStreamerID = `-- name: GetConfigByStreamerID :one
SELECT streamer_id,
       version,
       created_at,
       updated_at,
       for_trigger,
       for_label,
       against_trigger,
       against_label,
       memory_seconds,
       display_mode
FROM configs
WHERE streamer_id = $1
`

type GetConfigByStreamerIDRow struct {
	StreamerID     uuid.UUID
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ForTrigger     string
	ForLabel       string
	AgainstTrigger string
	AgainstLabel   string
	MemorySeconds  int32
	DisplayMode    string
}

func (q *Queries) GetConfigByStreamerID(ctx context.Context, streamerID uuid.UUID) (GetConfigByStreamerIDRow, error) {
	row := q.db.QueryRow(ctx, getConfigByStreamerID, streamerID)
	var i GetConfigByStreamerIDRow
	err := row.Scan(
		&i.StreamerID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForTrigger,
		&i.ForLabel,
		&i.AgainstTrigger,
		&i.AgainstLabel,
		&i.MemorySeconds,
		&i.DisplayMode,
	)
	return i, err
}

const updateConfig = `-- name: UpdateConfig :execresult
UPDATE configs
SET for_trigger     = $1,
    for_label       = $2,
    against_trigger = $3,
    against_label   = $4,
    memory_seconds  = $5,
    display_mode    = $6,
    version         = $7,
    updated_at      = NOW()
WHERE streamer_id = $8
`

type UpdateConfigParams struct {
	ForTrigger     string
	ForLabel       string
	AgainstTrigger string
	AgainstLabel   string
	MemorySeconds  int32
	DisplayMode    string
	Version        int32
	StreamerID     uuid.UUID
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateConfig,
		arg.ForTrigger,
		arg.ForLabel,
		arg.AgainstTrigger,
		arg.AgainstLabel,
		arg.MemorySeconds,
		arg.DisplayMode,
		arg.Version,
		arg.StreamerID,
	)
}
