// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/pscheid92/uuid"
)

type Config struct {
	StreamerID     uuid.UUID
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ForTrigger     string
	ForLabel       string
	AgainstTrigger string
	AgainstLabel   string
	MemorySeconds  int32
	DisplayMode    string
	Theme          string
}

type EventsubSubscription struct {
	StreamerID     uuid.UUID
	SubscriptionID string
	ConduitID      string
	CreatedAt      time.Time
}

type Streamer struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OverlayUUID    uuid.UUID
	TwitchUserID   string
	TwitchUsername string
}
