// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: streamers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/pscheid92/uuid"
)

const getStreamerByID = `-- name: GetStreamerByID :one
SELECT id,
       created_at,
       updated_at,
       overlay_uuid,
       twitch_user_id,
       twitch_username,
       access_token,
       refresh_token,
       token_expiry
FROM streamers
WHERE id = $1
`

func (q *Queries) GetStreamerByID(ctx context.Context, id uuid.UUID) (Streamer, error) {
	row := q.db.QueryRow(ctx, getStreamerByID, id)
	var i Streamer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OverlayUUID,
		&i.TwitchUserID,
		&i.TwitchUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
	)
	return i, err
}

const getStreamerByOverlayUUID = `-- name: GetStreamerByOverlayUUID :one
SELECT id,
       created_at,
       updated_at,
       overlay_uuid,
       twitch_user_id,
       twitch_username,
       access_token,
       refresh_token,
       token_expiry
FROM streamers
WHERE overlay_uuid = $1
`

func (q *Queries) GetStreamerByOverlayUUID(ctx context.Context, overlayUuid uuid.UUID) (Streamer, error) {
	row := q.db.QueryRow(ctx, getStreamerByOverlayUUID, overlayUuid)
	var i Streamer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OverlayUUID,
		&i.TwitchUserID,
		&i.TwitchUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
	)
	return i, err
}

const insertDefaultConfig = `-- name: InsertDefaultConfig :exec
INSERT INTO configs (streamer_id, created_at, updated_at)
VALUES ($1, NOW(), NOW())
ON CONFLICT (streamer_id) DO NOTHING
`

func (q *Queries) InsertDefaultConfig(ctx context.Context, streamerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertDefaultConfig, streamerID)
	return err
}

const rotateOverlayUUID = `-- name: RotateOverlayUUID :one
UPDATE streamers
SET overlay_uuid = uuidv7(),
    updated_at   = NOW()
WHERE id = $1
RETURNING overlay_uuid
`

func (q *Queries) RotateOverlayUUID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rotateOverlayUUID, id)
	var overlay_uuid uuid.UUID
	err := row.Scan(&overlay_uuid)
	return overlay_uuid, err
}

const upsertStreamer = `-- name: UpsertStreamer :one
INSERT INTO streamers (
    twitch_user_id,
    twitch_username,
    access_token,
    refresh_token,
    token_expiry,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (twitch_user_id) DO UPDATE
    SET twitch_username = EXCLUDED.twitch_username,
        access_token   = EXCLUDED.access_token,
        refresh_token  = EXCLUDED.refresh_token,
        token_expiry   = EXCLUDED.token_expiry,
        updated_at     = NOW()
RETURNING id,
          created_at,
          updated_at,
          overlay_uuid,
          twitch_user_id,
          twitch_username,
          access_token,
          refresh_token,
          token_expiry
`

type UpsertStreamerParams struct {
	TwitchUserID   string
	TwitchUsername string
	AccessToken    string
	RefreshToken   string
	TokenExpiry    time.Time
}

func (q *Queries) UpsertStreamer(ctx context.Context, arg UpsertStreamerParams) (Streamer, error) {
	row := q.db.QueryRow(ctx, upsertStreamer,
		arg.TwitchUserID,
		arg.TwitchUsername,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	var i Streamer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OverlayUUID,
		&i.TwitchUserID,
		&i.TwitchUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
	)
	return i, err
}
